import { it } from 'node:test';
import assert from 'node:assert/strict';
import { canonicalJson, sha256Hex } from '../contracts/validate.js';
import { readFileSync } from 'node:fs';
import { designRevision, renderScreen, renderStoredDesign } from '../runtime/design/index.js';
import { rendererFragments } from '../runtime/design/version.js';
import { errorCode, fixtureJson, fixtureText, input, stored } from './fixtures/design/helpers.mjs';

function reverseKeys(value) {
  if (Array.isArray(value)) return value.map(reverseKeys);
  if (value && typeof value === 'object') return Object.fromEntries(Object.entries(value).reverse().map(([k, v]) => [k, reverseKeys(v)]));
  return value;
}

it('(b) renders the complete vocabulary and entities byte-for-byte against golden HTML', () => {
  const result = renderScreen(input());
  assert.equal(result.html, fixtureText('golden-preview.html'));
  assert.equal(result.design_rev, fixtureJson('golden-identity.json').design_rev);
  assert.equal(result.tokens_digest, fixtureJson('golden-identity.json').tokens_digest);
  assert.ok(result.html.includes('A &amp; B &lt; C'));
  assert.ok(result.html.includes('&amp;amp; &lt;svg onload=&quot;alert(1)&quot;'));
  assert.ok(result.html.includes('&lt;/textarea&gt;&lt;script&gt;alert(3)&lt;/script&gt;'));
  assert.ok(result.html.includes('<button id="submit" class="button primary" data-element-ref="submit" type="button">'));
  assert.equal((result.html.match(/<link rel="stylesheet"/g) ?? []).length, 2);
  assert.doesNotMatch(result.html, /<script\b|<style\b|\sstyle\s*=|<svg\b|<img\b|<a\b/i);
});

it('(b,d) key order, repeated calls and record metadata do not change any generated byte', () => {
  assert.deepEqual(renderScreen(reverseKeys(input())), renderScreen(input()));
  const first = renderStoredDesign(stored());
  const other = stored('a', { client_event_id: 'cccccccc-cccc-4ccc-8ccc-cccccccccccc', recorded_at: '2026-10-01T00:00:00Z', generation: 9 });
  other.document.seq = 100;
  const next = renderStoredDesign(other);
  assert.equal(next.html, first.html);
  assert.deepEqual(next.stylesheets, first.stylesheets);
  assert.equal(next.design_rev, first.design_rev);
  assert.equal(first.design_input_seq, 7); assert.equal(next.design_input_seq, 100);
  for (let i = 0; i < 5; i++) assert.deepEqual(renderScreen(input()), renderScreen(input()));
});

it('(d) identity uses the independently encoded four-input canonical tuple', () => {
  const data = input();
  const tokens_digest = sha256Hex(canonicalJson(data.tokens));
  const expected = sha256Hex(canonicalJson([data.screen_ir, '1', tokens_digest, { model_id: 'synthetic-model', prompt_version: 'screen-v1' }]));
  assert.equal(renderScreen(data).design_rev, expected);
  const original = renderScreen(data);
  for (const change of [
    (d) => { d.screen_ir.title += '!'; },
    (d) => { d.tokens.space += 1; },
    (d) => { d.generator_id.model_id += '-other'; },
    (d) => { d.generator_id.prompt_version += '-other'; },
  ]) {
    const modified = input(); change(modified); const result = renderScreen(modified);
    assert.notEqual(result.design_rev, original.design_rev);
    assert.notEqual(result.html, original.html);
  }
  assert.notEqual(designRevision({ ...data, tokens_digest, renderer_version: '2' }), original.design_rev);
  assert.throws(() => renderScreen({ ...data, renderer_version: '2' }), errorCode('design_renderer_unsupported'));
  assert.throws(() => renderScreen({ ...data, renderer_version: '1/../other' }), errorCode('design_renderer_unsupported'));
  assert.throws(() => renderScreen({ ...data, generator_id: { ...data.generator_id, recorded_at: 'today' } }), errorCode('design_input_invalid'));
  for (const digest of [null, [tokens_digest], tokens_digest + '\n', tokens_digest.toUpperCase()]) {
    assert.throws(() => designRevision({ ...data, tokens_digest: digest }), errorCode('design_input_invalid'));
  }
  const generatorArray = []; Object.assign(generatorArray, data.generator_id);
  assert.throws(() => designRevision({ ...data, tokens_digest, generator_id: generatorArray }), errorCode('design_input_invalid'));
});

it('(d) two brands share immutable base CSS and have distinct canonical token resources', () => {
  const a = renderScreen(input('a')), b = renderScreen(input('b'));
  assert.deepEqual(a.stylesheets[0], b.stylesheets[0]);
  assert.notEqual(a.stylesheets[1].css, b.stylesheets[1].css);
  assert.notEqual(a.stylesheets[1].path, b.stylesheets[1].path);
  assert.ok(a.stylesheets[1].css.includes('--primary: #1144aa;'));
  assert.ok(b.stylesheets[1].css.includes('--primary: #cc8844;'));
  assert.equal(a.stylesheets[1].path, `tokens-${sha256Hex(canonicalJson(input().tokens))}.css`);
});

for (const hostile of fixtureJson('hostile.json').text) {
  it(`(b) renders hostile text inert: ${JSON.stringify(hostile)}`, () => {
    const data = input();
    data.screen_ir.title = hostile;
    data.generator_id.model_id = hostile;
    data.screen_ir.nodes = [{ kind: 'text', id: 'attack', text: hostile }, { kind: 'input', id: 'field', label: hostile, value: hostile, input_type: 'text' }];
    const { html } = renderScreen(data);
    assert.doesNotMatch(html, /<script\b|<svg\b|<img\b|<style\b/i);
    for (const tag of html.match(/<[^>]*>/g)) {
      assert.doesNotMatch(tag.replace(/"[^"]*"/g, '""'), /\s(?:style|on[a-z]+)\s*=/i);
    }
    assert.equal((html.match(/<main /g) ?? []).length, 1);
    assert.equal((html.match(/<input /g) ?? []).length, 1);
  });
}

it('(d) mutated or missing host projections are refused, with no fallback render', () => {
  const row = stored(); row.document.data.tokens.space = 10;
  assert.throws(() => renderStoredDesign(row), errorCode('design_input_invalid'));
  assert.throws(() => renderStoredDesign({ bytes: stored().bytes, document: {} }), errorCode('design_input_invalid'));
  assert.throws(() => renderScreen({ ...input(), design_input_seq: 0 }), errorCode('design_input_invalid'));
  const future = stored();
  const doc = JSON.parse(future.bytes); doc.data.screen_ir.renderer_version = '2';
  doc.data.screen_ir_sha256 = sha256Hex(canonicalJson(doc.data.screen_ir));
  future.bytes = Buffer.from(canonicalJson(doc)); future.document = { ...doc, seq: 7 };
  assert.throws(() => renderStoredDesign(future), errorCode('design_renderer_unsupported'));
});

it('(d) renderer version freezes byte-generating code, CSS and templates', () => {
  const sources = {};
  rendererFragments((name) => {
    sources[name] = readFileSync(new URL(`../runtime/design/${name}`, import.meta.url), 'utf8');
    return sources[name];
  });
  assert.deepEqual(Object.keys(sources).sort(), ['export-fragments/base-1.css', 'export-fragments/document.html', 'export.js', 'renderer.js']);
  for (const name of Object.keys(sources)) {
    assert.throws(() => rendererFragments((path) => sources[path] + (name === path ? '\n' : '')), errorCode('design_renderer_unsupported'));
    assert.throws(() => rendererFragments((path) => name === path ? undefined : sources[path]), errorCode('design_renderer_unsupported'));
  }
});
