import { canonicalJson } from '../../contracts/validate.js';
import { storedDesignInput } from './input.js';
import { renderScreen } from './renderer.js';

/** Raw HTML and Markdown link/image syntax never become executable markup. */
function markdownText(text) {
  return String(text).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/([\\`*_{}\[\]()#+.!|~-])/g, '\\$1').replace(/\r\n?|\n/g, '\n');
}

function markdownNode(node) {
  const text = markdownText;
  switch (node.kind) {
    case 'heading': return `${'#'.repeat(node.level)} ${text(node.text)}\n`;
    case 'text': case 'badge': case 'alert': return `${text(node.text)}\n`;
    case 'table': return `${text(node.label)}\n\n| ${node.columns.map(text).join(' | ')} |\n| ${node.columns.map(() => '---').join(' | ')} |\n${node.rows.map((row) => `| ${row.map(text).join(' | ')} |`).join('\n')}\n`;
    case 'divider': return '---\n';
    default: {
      const label = node.label ? `${text(node.label)}\n` : '';
      const value = node.value ? `${text(node.value)}\n` : '';
      const options = node.options ? `${node.options.map(text).join(', ')}\n` : '';
      const children = (node.children ?? []).map(markdownNode).join('\n');
      return label + value + options + children;
    }
  }
}

/** Regenerate from the checked durable input, rather than trusting mutable
 * caller-supplied HTML/CSS. No archive, filesystem or remote provider needed. */
export function exportDesign(record) {
  const input = storedDesignInput(record);
  const artifact = renderScreen(input, { exporting: true });
  const { screen_ir, tokens, renderer_version, generator_id } = input;
  const markdown = `# ${markdownText(screen_ir.title)}\n\n${screen_ir.nodes.map(markdownNode).join('\n')}\n`
    + `Generated by ${markdownText(generator_id.model_id)}; prompt ${markdownText(generator_id.prompt_version)}; renderer ${renderer_version}.\n`
    + `Design revision: ${artifact.design_rev}\n`;
  return { design_rev: artifact.design_rev, design_input_seq: artifact.design_input_seq,
    files: {
      'screen.html': artifact.html,
      'screens.json': canonicalJson([screen_ir]) + '\n',
      'tokens.json': canonicalJson(tokens) + '\n',
      'screen.md': markdown,
    } };
}
